title: Cristiano de Magalhães
logo: /assets/img/prof_pic_01.png
image: 'https://avatars.githubusercontent.com/u/68167970?v=4'
# description: text below image
# show_downloads: true # or false
# theme: jekyll-theme-minima
theme: minima # works fine
listing:
  - id: posts
    contents: posts/**/*/index.qmd
    type: grid
    fields: [image, date, title, subtitle, categories, author, reading-time]  
    sort: "date desc"
    #categories: cloud
    sort-ui: false
    filter-ui: false
    page-size: 3
about:
  template: jolla
  links:
    - icon: linkedin
      text: LinkedIn
      href: "https://www.linkedin.com/in/crisdemagalhaes/"
    - icon: github
      text: Github
      href: "https://github.com/cristiano-de-magalhaes"
comments: false
toc: false
